parameters:
    pjax.class: Strontium\PjaxBundle\Pjax
    pjax.twig.extension.class: Strontium\PjaxBundle\Twig\PjaxExtension
    pjax.kernel.event_listener.response.class: Strontium\PjaxBundle\EventListener\KernelResponseListener
    pjax.version_generator.auth_token.class: Strontium\PjaxBundle\VersionGenerator\AuthTokenGenerator

services:
    pjax:
        class: %pjax.class%
        arguments:
            - @request_stack

    pjax.twig.extension:
        class:  %pjax.twig.extension.class%
        arguments: [ @pjax ]
        tags:
            - { name: twig.extension }

    pjax.version_generator.auth_token:
        class:        %pjax.version_generator.auth_token.class%
        arguments: [ "@security.context"]

    pjax.kernel.event_listener.response:
        class: %pjax.kernel.event_listener.response.class%
        public: false
